[build]
  publish = "."

[[redirects]]
  from = "/projects"
  to = "/pages/projects.html"
  status = 200

[[redirects]]
  from = "/projects/*"
  to = "/pages/projects/:splat.html"
  status = 200

[[redirects]]
  from = "/experience"
  to = "/pages/experience.html"
  status = 200

[[redirects]]
  from = "/project"
  to = "/pages/project.html"
  status = 200
